CI: verify-trigger: only trigger on tags

diff --git a/.github/workflows/verify-tag.yaml b/.github/workflows/verify-tag.yaml
--- a/.github/workflows/verify-tag.yaml
+++ b/.github/workflows/verify-tag.yaml
@@ -3,30 +3,34 @@ name: Verify Tag
 on:
   workflow_run:
     workflows: ["Build"]
-    types:
-      - completed
+    types: [completed]
+    branches:
+      - "refs/tags/*"  # Only trigger on tags
 
 jobs:
   verify-release-tag:
-    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/')
     runs-on: ubuntu-24.04
+    if: github.event.workflow_run.conclusion == 'success'
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          fetch-tags: true
 
       - name: Install Rust toolchain
         uses: dtolnay/rust-toolchain@stable
 
       - name: Verify Git Tag Matches Cargo Version
         run: |
+          TAG=$(git describe --tags --exact-match || echo "untagged")
           CARGO_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
-          GIT_TAG=$(git describe --tags --exact-match || echo "untagged")
 
           echo "Cargo.toml version: $CARGO_VERSION"
-          echo "Git tag: $GIT_TAG"
+          echo "Git tag: $TAG"
 
-          if [[ "$GIT_TAG" != "$CARGO_VERSION" ]]; then
-            echo "Error: Tag ($GIT_TAG) does not match Cargo.toml version ($CARGO_VERSION)!"
+          if [[ "$TAG" != "$CARGO_VERSION" ]]; then
+            echo "Error: Tag ($TAG) does not match Cargo.toml version ($CARGO_VERSION)!"
             exit 1
           fi
 
